title: "Tung Nguyen - Portfolio"
email: tung051024@gmail.com
description: "Security student â€” lab reports, projects, and write-ups."
baseurl: ""
url: "https://tung05.github.io"

remote_theme: "jekyll/minima"
minima:
  skin: dark

header_pages:
  - index.md
  - projects/index.md

# Blog / pagination settings
paginate: 5

# Files to exclude from the site
exclude:
  - README.md
